# Associations QC



```{r, echo=FALSE}
library(png)
library(grid)
```

```{r, echo=FALSE}
working_dir="/home/labs/davidgo/Collaboration/L4_MPRA/"
output_dir=sprintf("%s/test_QC",working_dir)
```


## Barcodes per cCRE

This is a placeholder for an explanation on the analysis

```{r,echo=FALSE}


bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/Max_MPRA_run2/Barcodes per cCRE.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/PMID_38766054_Reilly/Barcodes per cCRE.png",native = T)

# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```

## PCR bias - GC content

```{r,echo=FALSE}


bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/placeholder.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/PMID_38766054_Reilly/PCR bias - GC content.png",native = T)


# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```



```{r,echo=FALSE}


bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/placeholder.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/Max_MPRA_run2/PCR bias - GC content summary.png",native = T)


# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```

## PCR bias - G Stretch



```{r,echo=FALSE}


bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/placeholder.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/thylacine biorxiv Gallego Romero/PCR bias - G-stretches.png",native = T)


# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```

```{r,echo=FALSE}


bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/placeholder.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/Max_MPRA_run2/PCR bias - G-stretches summary.png",native = T)


# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```


## cCRE-barcode observations

```{r,echo=FALSE}


bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/Max_MPRA_run2/cCRE-barcode observations.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/PMID_38766054_Reilly/cCRE-barcode observations.png",native = T)


# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```

## Retained cCREs

```{r,echo=FALSE}


bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/Max_MPRA_run2/Retained cCREs.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/PMID_38766054_Reilly/Retained cCREs.png",native = T)

# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```

## Barcode promiscuity

```{r,echo=FALSE}


bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/thylacine biorxiv Gallego Romero/Barcode promiscuity.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/PMID_38766054_Reilly/Barcode promiscuity.png"
,native = T)

# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```

## Downsampling - Retained cCREs

```{r,echo=FALSE}



bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/L3a2_281122/Downsampling - Retained cCREs.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/Max_MPRA_run2/Downsampling - Retained cCREs.png",native = T)

# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```


## Downsampling - Barcodes per cCRE

```{r,echo=FALSE}



bad_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/Max_MPRA_run2/Downsampling - Barcodes per cCRE.png",native = T)
good_example <- readPNG("/home/labs/davidgo/Collaboration/MPRA_QC_pipeline/associations/output/L3a2_281122/Downsampling - Barcodes per cCRE.png" ,native = T)

# Start new page and define layout
grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2)))

# Helper to specify location in layout
vplayout <- function(row, col) viewport(layout.pos.row = row, layout.pos.col = col)

# Draw both images in the layout without using print()
pushViewport(vplayout(1, 2))
grid.raster(bad_example, interpolate = FALSE)
popViewport()

pushViewport(vplayout(1, 1))
grid.raster(good_example, interpolate = FALSE)
popViewport()
```
