# Input format 
The QC pipeline is organized into two main chapters: cCRE-BC association, and RNA and DNA quantification.
Each chapter is accompanied by a dedicated script that allows the user to run all analyses presented in this book.

We provide a description of the files required to run the pipeline in a separate PDF file. Alongside each analysis, you will find the input files needed in order to run it. Example files format is provided below.

## Associations
### Script
association_analysis.py

### Input

Input files description is provided in *filename.pdf*


### Output

Output figures for the cCRE-BC association analyses, generated by the pipeline, are presented in the chapter: 2. Associations QC


## RNA and DNA quantification


### Script
activity_analysis.py


### Input

Input files description is provided in *filename.pdf*


### Output

Output figures for the RNA and DNA quantification analyses, generated by the pipeline, are presented in the chapter: 3. Activity QC


